#!/bin/bash

GH_PAGES_SOURCES="docs/source quickavro docs/Makefile"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
NEW_COMMIT_MESSAGE=$(git log ${CURRENT_BRANCH} -1 --pretty=short --abbrev-commit)

pushd ..
git checkout gh-pages
rm -rf build _sources _static
git checkout ${CURRENT_BRANCH} ${GH_PAGES_SOURCES}
git reset HEAD
popd
make html
mv -fv build/html/* ..
pushd ..
rm -rf ${GH_PAGES_SOURCES} docs/build/html
git add -A
git commit -m "Generated gh-pages for ${NEW_COMMIT_MESSAGE}" && git push origin gh-pages 
git checkout ${CURRENT_BRANCH}
